server {
    listen 80;
    server_name localhost;

    # Arahkan root ke folder public milik Laravel
    root /var/www/public;
    index index.php index.html index.htm;

    # Optimasi kompresi GZIP
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;

    # Routing SPA / Laravel (jika file tidak ada, arahkan ke index.php)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass eksekusi PHP ke container 'app'
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Keamanan tambahan: Tolak akses ke file tersembunyi
    location ~ /\. {
        deny all;
    }
}
